name: Update keys

on:
  
  schedule:
    - cron: '*/10 * * * *'  # Runs the job every 10 minutes
  workflow_dispatch: null

jobs:
  update:
    name: Update keys
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Get headers
        run: |
          python main.py

      - name: Checkout keys branch
        uses: actions/checkout@v4
        with:
          ref: keys
          path: key_repo

      - name: Update key if it differs
        run: |
          file=headers.json
          cd key_repo
          echo "Old -> $(cat $file) || New -> $(cat ../$file)"
          if [[ "$(cat $file)" != "$(cat ../$file)" ]]; then
            cp ../$file .
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add $file
            git commit --amend -m "chore: Updating key"
            git push --force
          fi
